// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using FRILTimeMachine.CRaceJSONDataJsonTypes;

namespace FRILTimeMachine
{

    internal class CRaceJSONData
    {

        [JsonProperty("position")]
        public int Position { get; set; }

        [JsonProperty("pilot")]
        public Pilot Pilot { get; set; }

        [JsonProperty("lap_count")]
        public int LapCount { get; set; }

        [JsonProperty("avg_lap_time")]
        public int AvgLapTime { get; set; }

        [JsonProperty("fastest_lap")]
        public FastestLap FastestLap { get; set; }

        [JsonProperty("last_lap")]
        public LastLap LastLap { get; set; }

        [JsonProperty("latest_tracked")]
        public bool LatestTracked { get; set; }
    }

}
