// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using FRILTimeMachine.CRaceJSONDataJsonTypes;

namespace FRILTimeMachine.CRaceJSONDataJsonTypes
{

    internal class FastestLap
    {

        [JsonProperty("lap_num")]
        public int LapNum { get; set; }

        [JsonProperty("lap_time")]
        public int LapTime { get; set; }
    }

}
