// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using FRILTimeMachine.CRaceJSONDataJsonTypes;

namespace FRILTimeMachine.CRaceJSONDataJsonTypes
{

    internal class Image
    {

        [JsonProperty("url")]
        public object Url { get; set; }
    }

}
